define malloryGoddessEpilogueArtMediaPath = 'media/v077/MalloryEpilogue/'

image EliasEpilogueTyingElias = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue1a.webp'
image EliasEpilogueTyingEliasWithBJ = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue1b.webp'
image EliasEpilogueForcingEliasOral = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue2a.webp'
image EliasEpilogueForcingEliasOralNut = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue2b.webp'
image EliasEpilogueEliasOralFootLick = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue3a.webp'
image EliasEpilogueEliasOralFootLickNut = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue3b.webp'
image EliasEpilogueEliasOralCumkiss = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue3c.webp'
image EliasEpilogueAssEating = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue4a.webp'
image EliasEpilogueAssEatingNut = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue4b.webp'
image EliasEpilogueFootLickers = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue5.webp'
image EliasEpilogueMalloryFucksPlayer = malloryGoddessEpilogueArtMediaPath + 'EliasEpilogue6.webp'

label malloryEpilogueAddendum:
    # (Gay content is prepended by the double slash, // )

    call expression "showDateTitleCard" pass (dateTitle = 'The Other Kind of Conquest')
    play music 'media/v075/mallory/audio/m_rousing.mp3'
    scene EliasEpilogueTyingElias with dissolve
    concubine 'Y-you don’t have to do this...'
    'Mallory looks down on him with a gentle smile devoid of mercy. She’s wetting her lips, as if a luxurious feast has been laid out before her. '
    'I suspect she is, by now, familiar with the feeling.'
    'And this is exactly how it should be. I wish her happiness beyond measure, no matter what it takes. No matter what she wants.'
    'She sits on the edge of the concubine’s own bed, gently kicking off her shoes. She looks perfectly at ease.'
    'At this point, I’ve set about binding the concubine with the (quite strong) ceremonial silk ribbons that I wear around my own wrists. He struggles, pointlessly—I must’ve done this a hundred times by now.'
    '...wow, I’ve done this a hundred times?'
    concubine 'Please, I don’t--'
    'I squeeze him firmly. Not so much as to hurt him, but enough to remind him of the situation. '
    player 'Hush.'
    'And then, softer,'
    player 'We’ll take care of you.'
    if store.malloryGayHarem:
        # Gay start
        mallory 'He makes such pretty noises, First Male. You ought to silence them.'
        'I meet his gaze as he kneels before me. The hesitation in his eyes makes my heart flutter.'
        'The futa have rubbed off on me. In more than the expected way, I mean.'
        'These males are mine while Mallory is gone. Anything I want from them, I can take...and the vulgar power of that is still thrilling.'
        'I expect it always will be.'
        '...and besides, this boy is just so damned cute, trembling like that.'
        scene black with dissolve
        'I clasp my hands around his cheeks, and lean down to press my lips to his.'
        'He flinches. My cock twitches.'
        'His lips are soft and glossy, and he tastes ever so faintly of coconut. I want more of him.'
        'My tongue slips greedily into his mouth, a moan bubbling past my throat as I savor my conquest.'
        'Mallory doesn’t bother to hide her twitching hard-on, nor the triumphant smirk on her face as I spend the next few seconds forcibly suckling Elias’ tongue.'
        mallory 'Goodness. I hadn’t expected such enthusiasm, [store.playerName].'
        'The purring in her voice sets my heart ablaze. I break the kiss with the concubine, licking my lips to prolong his taste upon them.'
        'He can no longer meet my gaze. I seem to have humiliated him somewhat~'
        '...Goddess. I can’t help myself.'
        'My cock springs up, twitching against his lips. I feel the heat of his breath cascading down my balls as he shudders. It feels like the caress of a fucking angel.'
        'Mallory’s eyes widen. So does her grin.'
        mallory '...do it.'
        scene EliasEpilogueTyingEliasWithBJ with dissolve
        'I oblige her, shuddering in hedonistic abandon as the silky warmth of his tongue envelops me. But the concubine’s jaw parts for me, even though I can see the discomfort in his face, plain as day.'
        'I come to understand why as I languidly pump my cock in his mouth, biting my lip as the gentle waves of pleasure travel down to my tiptoes.'
        'He holds too still - he wants to buy himself time, perhaps even thinking of this as a way to weasel out of his obligation to My Eminence. Sucking my cock instead of hers.'
        'It’s no use, of course. But I see no reason to stop him, either...'
        'Long, luxurious strokes, savoring the feeling of this cute little servant’s mouth wrapped snugly around my cock, until precum drools sweetly from the tip.'
        'I fuck his tongue nice and slow, reveling in the way it caresses me, the way it caves around my head as I plunge into his mouth.'
        'I won’t cum yet. No, that’s for later. I’d much prefer to sustain the lusty high a while longer. Slip free of those mental restraints a little.'
        'I let him warm my cock, though, stroking my fingers through his hair, watching the way it makes him shiver.'
        player 'Your Eminence should have the first orgasm. There’ll be plenty of time for me to use him when he’s more pliable.'
        mallory 'I’m looking forward to it...~'
    # Gay end
    scene black with dissolve
    'Mallory spreads her legs, and beckons me with a finger.'
    mallory 'Bring him here. I want my cock in his mouth...now.'
    'Hollow noises spout from his lips as I push him onto the bed. It’s amazing he has so much stamina left after spending all that time half-frozen outside.'
    'He’ll make an excellent addition to our harem.'
    'With some indelicate grunts and swearing, I manage to put him down on his knees between Mallory’s legs, my grip gentle but firm as I push his head down and towards Mallory’s holy scepter.'
    'She is perfectly at ease, not so much as lifting a finger, while I clamp my fingers into the boy’s jaw, guiding it open—'
    'And letting Mallory’s cock slide into his mouth. He wriggles blindly, like an animal, but my efforts keep him pinned.'
    player 'My gift to you, my Goddess. '
    mallory 'Haha, wow. He’s squirming a lot.'
    'She adjusts herself slightly, leaning back against the luxurious array of pillows as she begins to slowly fuck his mouth.'
    mallory 'Mnnnhh, but it feels really good...'
    scene EliasEpilogueForcingEliasOral with dissolve
    'She doesn’t stand on ceremony for much longer. The next thing I know, Mallory’s palm is clasped around the back of my head, and she draws me in with tender desire, as the concubine’s tears begin to run down her cock.'
    'Our lips meet. The taste of morning dew clings to them, and we rock back and forth together in the morning sunlight as she drives her needy futa cock down his throat.'
    'Everything feels absolutely perfect in the world.'
    'Minutes pass too quickly. I want them to last forever. But she pulls away after a long, heady kiss, the taste of her tongue still fresh in my mouth as she whispers.'
    mallory 'Do you want to know a secret?~'
    mallory 'I’m close~'
    player 'Yeah~?'
    'She nods.'
    mallory 'Yeah. I’m gonna cum...'
    mallory 'I’m gonna cum in his mouth...'
    mallory 'Hold him for me...'
    player 'Yes, my Goddess...!'
    'He hears her. I know he hears her. The noises he makes, of helplessness and hopelessness, all crashing down at once....'
    'He only has seconds left, as an unbound male. And he knows it.'
    'I hold him steady, while Mallory languidly brings herself closer and closer to orgasm, pumping her hips in an unsteady rhythm...'
    'Until her eyes close ever so slightly, and she emits a delicious moan. '
    mallory 'Hey [store.playerName]...~?'
    player 'G-Goddess?'
    mallory 'I’m cumming...'
    scene EliasEpilogueForcingEliasOralNut with dissolve
    pause 0.5
    pause 1
    pause 0.5
    pause 0.5
    # so that a player who is frantically clicking wont accidentally skip
    scene black with dissolve
    'The boy on her cock is rendered silent, as she pumps her load into his mouth.'
    'Once more, she pulls me into a kiss. The concubine’s performative obstinacy dwindles with every thrust of her cock, as she pumps his tummy full of holy venom and his mind fizzes with ecstasy.'
    'By the time Mallory has finished busting her nut, it’s all he can do just to squirm a little bit, his eyes unfocused.'
    stop music fadeout 2.5
    'And yet... '
    'I can still sense it, some bratty ember of defiance in him.'
    'Mallory spots it too.'
    play music 'media/v06/Routes/Claudia/Audio/m_interrogation.mp3'
    mallory 'Hm.'
    mallory 'We’re not done with him. But you can let him go for now.'
    'I nod, and let up on him, resting on the end of the bed as a sudden weariness washes over me. She keeps herself hilted in his mouth.'
    'He tries to slide off and away, tries to assert himself even in his state of haze. But Mallory does not allow this. '
    mallory 'Willful child, your place is with your Goddess. You are being disobedient.'
    'Her hands clasp over his head, and a pretty smirk lights up her face as she languidly drapes her leg around his back. He gags, as Mallory’s cock is hilted fully in his cum-slicked throat.'
    scene EliasEpilogueEliasOralFootLick with dissolve
    'My Goddess, I love her.'
    'Her other leg stretches towards me. Her bare sole boops the bridge of my nose, and for a moment, I lock eyes with my Goddess.'
    'I know exactly what to do.'
    'My lips part. My tongue eagerly meets the arch of her soft, flawless footsie, drawing it upwards until I lay a soft, loving kiss upon the tips of each of those cute, wiggling toes.'
    'All the while, she delights in fucking the boy’s mouth a little more. She’s taking her time, appreciating the richness of the moment.'
    'One male worshipping her cock, another worshipping her feet.'
    'I can see the way she licks her lips, the way her eyes flutter as I playfully suck at her toes and gently kiss up and down her heels.'
    'When she speaks, minutes later, she does so in a dreamlike hum, never breaking her slow, steady rhythm of using his mouth like a fleshlight.'
    mallory 'What’s this one’s name, my love?'
    'I pause, collecting myself with a mild gulp.'
    player 'Elias, your Eminence.'
    mallory 'Mm...Eliaaaas...'
    'She stretches the name. Savors it. She lets it linger on her lips like sugar, savoring the identity she’s burning away.'
    mallory 'I want you to know, Elias...before I bind you...'
    mallory 'You will be treasured~'
    '...'
    '...or maybe she means he\’ll be her favorite toilet...'
    'He can’t resist her. But I can see the abject humiliation in his eyes, as Mallory’s balls slowly begin to churn, and seize...'
    'I lavish attention on the soft, delicate, sensitive underside of her feet while she begins to fill his mouth with cream. She rubs her heels into my face, curls her toes in my hair, and my tongue encourages her with a long, passionate stroke with every gush that she spills into Elias’ mouth.'
    scene EliasEpilogueEliasOralFootLickNut with dissolve
    pause 0.5
    pause 1
    pause 0.5
    pause 0.5
    scene black with dissolve
    'Despite himself, Elias swallows. Slowly at first, with effort, but within just a few seconds, he takes a steady series of little sips, while the excess begins to flow like molten silver down his chin.'
    mallory 'Ahhh...'
    mallory 'That was fun~'
    'She boops me on the nose with the ball of her foot again, and quickly pulls Elias up and off her cock, cradling his chin as she looks him in the eyes.'
    mallory 'See how generous your Goddess is~? '
    concubine '...frrhnuu...'
    mallory 'Mm? Speak up.~'
    'His eyes are rolled up towards the ceiling. His breathing is shallow, his strength drained. '
    'But the words that leave his lips raise my eyebrows.'
    stop music
    concubine 'Crazy...bitch...'
    mallory '...'
    mallory 'Oh, wow. You’re still with us? After all that?'
    mallory 'Determined boy!'
    'She brushes the hair from his eyes, smiling softly. Sunlight catches her face, and lights up Elias’ hair for a moment.'
    play music 'media/v06/Routes/Claudia/Audio/m_angel.mp3'
    mallory 'Once more, then~'
    player 'Again, your Eminence?'
    mallory 'Mhm. Our newest charge seems hellbent on sabotaging us by taking up my entire morning. I must admit, it’s working.'
    mallory 'But the duties of the day will keep for a while yet...'
    # Gay start
    if store.malloryGayHarem:
        mallory 'And I daresay you were having plenty of fun earlier for the both of us. '
        'She beckons me with a finger once more.'
        'I dutifully crawl up next to her on the bed, prostrating myself submissively as she wraps her other leg snugly around my shoulders, just as she does with Elias.'
        'I find myself staring into his eyes for a moment. He fights in vain to focus them, let alone express his impotent wrath.'
        'It’s cute as hell. A sweet shiver courses through me - I look forward to fucking him more often.'
        'For now, though, Mallory’s needs are clear. Her hand coils in Elias’ hair, holding him firmly in place as his jaw slackens, and a thick puddle of her cum oozes out...'
        mallory 'Don’t let him spill that.'
        scene EliasEpilogueEliasOralCumkiss with dissolve
        'I lean across, moaning as I crush my lips forcefully against his all over again, the thick trickling cream buzzing bright and clear upon my lips as my eyes flutter shut in cozy bliss.'
        'Mallory lets me take my time, resting for the most part, albeit watching me invade Elias’ soft, tasty mouth with insatiable hunger.'
        'I find my hands moving of their own accord, touching and stroking through his hair, holding him closer, so that I might deepen our delicious kiss. '
        'The only thing that I allow to interrupt the sordid dance between my invasive tongue and his is Mallory’s faintly twitching cock, which she none too subtly pushes between us, forcing me to kiss him around her.'
        'I know she’s just establishing who this is really all for. But she needn’t remind me. I’d do anything and everything for my Goddess.'
        'The twisted orgy continues just like that for a few minutes longer, until Mallory is hard again, signalling such by casually pushing me away, and hilting herself in his mouth. '
        scene black with dissolve
        'She breathes a sweet, melodic sigh.'
    # Gay end
    scene EliasEpilogueAssEating with dissolve
    'With no further words, Mallory rolls Elias upon his back, taking full advantage of his half-hazed state. '
    'All he can do is squirm as she lines her cock up with his mouth, the weight of her divine ass hovering above his head like a guillotine waiting to drop.'
    'She slips her cockhead past his lips with infinite relish, and winks to me with a sly, conspiratorial smile.'
    mallory 'This one’s gonna do it, you know.~'
    player 'Y-yes, my Goddess...'
    mallory 'Hnnf.'
    'Her gaze turns back towards me, passion alight in her eyes like dancing flame as she teasingly wiggles her generous rump back at my face.'
    'She needs no words. I hurry to wrap myself snugly around her ass, and swiftly press my lips to that sweet, soft pucker, my tongue diving deep to find just the right spots.'
    'Amidst her moans and steady riding of her plaything’s face, she mumbles a question in that special singsong voice of hers.'
    mallory 'You suuuuuure you don’t want to try and save him?~ '
    'Ah. She’s toying with me. Or him.'
    '...or maybe both of us.'
    'Either way, I withdraw my lips with a wet POP and shake my head.'
    player 'He belongs at your feet, my Goddess.'
    mallory 'Mnnh...Well, you heard him, my little morsel!~'
    'She savors him like a delicacy. Which, to be fair, he is. A male as chaste and as handsome as Elias is increasingly rare, in the Empire and without.'
    'And she’s just going to fuck him raw like this, and use him as a private urinal.'
    'Decadence beyond decadence.'
    'I love my Goddess.'
    scene black with dissolve
    'I show her as much with the ceaseless motion of my aching tongue, drawing sighs and moans from her lips, encouraging her to hump Elias’ pert, soft lips.'
    'I make her toes curl, her back arch in ecstasy as I worship her sweet divine ass.'
    'All to help her cum one last time in his mouth. Participating in his binding...'
    'Helping her take everything from him.'
    'I can’t help myself. My hands fall between my own thighs, and I start pumping my own cock furiously.'
    'I know my Goddess can see me do it. I see the way she smirks as she reaches back to pull me deeper between her bouncing cheeks.'
    'A shuddering moan escapes my throat.'
    mallory 'Mnnhhh...'
    mallory 'Soon...!'
    'She tenses. I feel her clench around my tongue. Triumph shines like starlight in her eyes.'
    scene EliasEpilogueAssEatingNut with dissolve
    'A final eruption of divine venom pumps over his tongue. I feel every orgasmic pulse as Mallory’s asshole grips me firmly, forcing me to watch the fruits of my labor.'
    'Even as my Goddess\' cream leaks out of his nose, Elias can\'t stop himself from swallowing.'
    'He’s hooked, by now.'
    mallory 'Good boy. Now drink from my cock~'
    scene black with dissolve
    'As she pumps that fresh nut in his slackened mouth, Elias falls deeper and deeper into the haze’s terrible warmth.'
    'Within just a few more gushes of Mallory’s gift, he’s willingly gulping her down.'
    'And by the time she’s finished, he is eagerly suckling at her gently twitching shaft, moaning weakly as she pulls it from his lips with a delighted gasp.'
    mallory 'Mine~'
    player 'Three times in a row!'
    mallory 'Please. I’ve got love to give for days.'
    'Nonetheless, with her charge rendered a desperate, dick-suckling boy slave, she seems to ease up, reclining back into her splendid pillows, spreading her legs to either side.'
    'She curls her toes slowly, restfulness and contentment lidding her gaze as she peers over them, down upon us, her servants, her lovers, her boys of worship.'
    'The boy lays mostly still for a few seconds, blinking slowly as his new truth tightens its vice grip on his mind. His eyes are wide as plates as he looks to Mallory.'
    concubine 'C-can...I have more...?'
    mallory 'Oh, you’ll have plenty to swallow...'
    mallory 'But for now, you see that other cute little morsel there?'
    mallory 'You listen to him as you would me, understand?~'
    mallory 'He’s your best friend now. You’d do anything for your best friend, wouldn’t you?'
    'The concubine looks between the two of us for a few moments, and soon decides to crawl down to the foot of the bed to join me, a drunken smile playing on his lips as he nods.'
    concubine 'S-sorry about earlier...'
    'I shake my head and give him a quick pat.'
    'But before I can “forgive” him, Mallory’s soles press snugly against his cheek...and mine.'
    'He looks confused. So of course I have to show him how it’s done.'
    scene EliasEpilogueFootLickers with dissolve
    'My jaw is burning with exertion and my tongue is sore, but I perservere, for her. And soon, the boy catches on.'
    'Mallory sighs as our tongues dance upon her heels and her arches and her soft, silky toes. Her cock is twitching gently in her lap.'
    'He looks so happy now.'
    'Those lights dancing in his eyes.'
    'The way he worships his Goddess’ feet with his suckling lips and silky tongue...'
    'This is his life, now.'
    'And mine.'
    scene black with Dissolve(3)
    stop music fadeout 2.5
    '...'
    'The Goddess be praised.'
    $ persistent.Mallory_YetAnotherHorribleAssholeMaleBreakingFuta_Unlocked = True
    $ renpy.end_replay()
    jump gameFinished
