# Buttfucked To Death In A Thai Comfort Camp
# (Black screen)
label summerCampForSluts:
    call expression "showDateTitleCard" pass (dateTitle = 'Comfort Boy')
    play music 'media/v06/Routes/Rye/Audio/m_aftermath.mp3'
    play sound 'media/v06/Routes/Rye/Audio/Car.mp3'
    '...'
    '...'
    'Everything hurts.'
    'There\'s a bag on my head.  I\'m tied up. Its cold out, but I\'m sweating.'
    'I hope I get cum soon. Everything aches.'
    'I think the droning of the engine is grinding into my mind. I\'m cramped in the bed of this truck, and it feels like all my limbs are bent the wrong way.'
    'I can feel the wind on my bare skin, or is that...someone\'s breathing?'
    'I let out a soft moan. I hope they can\'t hear me.  They won\'t feed me and besides, they\'d hit me.'
    '...my balls feel swollen, like someone hit them an hour ago, but no one did.  Did they? Is this just cum withdrawal?'
    voice 'Hm, wanna grab a male from the back? I\'m ready for a break.'
    'Hands roughly grab me and futahandle me out of the back. My bare feet set down on cold dirt, and someone pushes me until I\'m bent over the tailgate.'
    'My rescuing angels are talking to each other.'
    angel1 'What the fuck?  That\'s a male??'
    angel1 'How...'
    angel1 'How fucking long has he been in here?'
    angel2 'Our relief was delayed.  Turns out war can make the mail run slow.'
    angel2 'Listen, Gloria…'
    angel2 'Penal legion troops are animals.  I saw one fuck a dog on a bet.  If he were dead, I bet they\'d still fuck him till he cooled.  This…'
    'I flinch as her palm claps against my ass.'
    angel2 'This will do just fine.'
    gloria 'But...'
    angel2 'So do you want to fuck his holes or not?'
    gloria '…...yeah, awright. '
    'One of the angels grabs my head and brings it to her dick.'
    'Oh glorious day!  A cock! A real cock I can put in my mouth!'
    angel2 'Hungry little turd, ain\'t he? '
    'I feel a strong hand grip my swollen, aching balls, and tug. I let out a squeak, and she laughs.'
    gloria 'That\'s not nice...'
    angel2 'Listen.'
    angel2 'If you\'re gonna be working at the front, you need to toughen up.'
    'Her grip on my balls gets a little tighter, sending holy light searing through my body.'
    gloria 'Yeah, but...it\'s not like we\'re soldiers, we just work with them.'
    'She grabs my legs and spreads my ass.'
    angel2 'So he\'s for the troops.  It\'s not unpatriotic if we use him. '
    'The Angel who gifted my mouth with her cock slaps my ass again.'
    angel2 'They\'re rough bitches at the front.  '
    angel2 'They like their meat tender.'
    gloria 'Well…I GUESS I could...'
    'I feel someone spit on my asshole. I arch my back, hoping someone will stuff a cock in there.'
    'Someone does.'
    'She tears away the bag over my head, and I blink in the sudden, searing light.'
    # (Splash page. Player is getting spit roasted by a pair of uniformed futa in the bed of a truck. He has some scratches, but let\'s keep the damage cosmetic and sexy. Mouth futa looks kind of conflicted; ass futa looks mean.)
    scene summerCampTruckFuck with slowFadingFlash
    show summerCampTruckFuckLoop
    $ persistent.DeathcampUnlocked = True
    'I let out a moan around the fat cock in my mouth. It has been too, too long since I was stuffed like this, and I need it desperately.'
    angel2 'Heh. '
    angel2 'Greedy little whore, isn\'t he? '
    gloria 'Maybe...being a comfort boy is best for him. I mean, he\'s bound as all hell, and it looks like he could use a meal or thirty...'
    angel2 'Yeah! We\'re doing him a favor with this appetizer! '
    'The cock in my ass feels almost like it\'s splitting me in half...and I love it.'
    'I gag just a little as the futa in front of my pumps my throat.'
    'With each thrust I can feel my old self die.  I\'m not...whatever my name was.'
    '......what was my name?'
    '...'
    'No matter. I\'m a receptacle.  A empty place for futa to put their cocks into.'
    'I thrust back, driving the cock in my ass deeper into me.'
    gloria 'Okay, you were right. He loves it.'
    angel2 'Told ya!'
    angel2 'Awright, let\'s finish and get back on the road.'
    'I can feel my body opening in preparation of receiving their seed. My eyes are rolling back in my head.'
    gloria 'Ahem. Uh… '
    'She looks abruptly a little shy.'
    gloria '...in nomine matris, pedicabo ego vos et irrumabo.'
    angel2 'Oh! Huh, I didn\'t know you were THAT religious.'
    gloria 'I mean, I don\'t make a big deal of it…'
    angel2 'I\'ve just...never seen anyone quote scripture when they cum before?'
    gloria 'It\'s Saint Catella\'s Prayer, you say it whenever you feed a male.'
    gloria 'Just drop it, okay? '
    'They blast into me.  I spasm and choke as the flood of jism pumps down my throat, and I can feel cum leaking out of my ass.'
    'Almost immediately I feel my body relaxing, and the pain leaving. It had been so, so long since I took a load...almost a day?'
    angel2 'Amen. '
    angel2 'Awright, break\'s over.'
    angel2 'Let\'s get him back into the truck. I\'d say he\'s ready for his new life...'
    # (Black screen)
    show black with Dissolve(3):
        alpha 0.5
    'I wonder why I ever resisted this.'
    show black with Dissolve(3):
        alpha 1.0
    'I am at peace.'
    $ renpy.end_replay()
    # (GAME OVER)
    jump gameOver
